export interface ProfileContent {
  name: string;
  initials: string;
  githubUrl: string | null;
  linkedinUrl: string | null;
  email: string | null;
  resumePath: string | null;
  resumeFileType: string | null;
  portraitPath: string | null;
}

export const profile: ProfileContent = {
  name: 'Nitin Kotcherlakota',
  initials: 'NK',
  // Verified from this repository's own git remote (github.com/knitinjaideep/personal_portfolio).
  githubUrl: 'https://github.com/knitinjaideep',
  // Verified public LinkedIn profile URL, per résumé content audit.
  linkedinUrl: 'https://www.linkedin.com/in/nitin-kotcherlakota/',
  email: 'nitin.kotcherlakota@gmail.com',
  // Generated by `npm run resume:pdf` (see src/content/resume.ts and
  // scripts/generate-resume-pdf.mjs) and stored at public/resume/.
  resumePath: '/resume/nitin-kotcherlakota-resume.pdf',
  resumeFileType: 'PDF',
  // Approved real portrait, see src/assets/images/nitin-portrait.jpg. The
  // Portrait component imports the file directly through Next.js static
  // image handling; this string is used only as an "is a portrait set"
  // flag and for documentation.
  portraitPath: '/src/assets/images/nitin-portrait.jpg',
};
